### ISSUE TITLE
Bug report: AssertionError assert weight_matrix.sum() == n_size

### ISSUE THREAD

**Issue by u-masao** [u-masao/embed-text-recommender#17]
Gradio UI で推論中に発生。モデルの出力やベクトルの結合処理が怪しい。

commit: 1072f3e4957ccbaf42cda3f26c9224441bd89c55
 
```:ui.yaml
ui:
  gradio_share: True
  embedding_model:
    # oshizo/sbert-jsnli-luke-japanese-base-lite
    # intfloat/multilingual-e5-small
    # intfloat/multilingual-e5-base
    intfloat/multilingual-e5-large
  vector_engine:
    models/intfloat/multilingual-e5-large/engine_chunk_split.cloudpickle
  sentences_data:
    data/interim/sentences.parquet
  default_query: エンジニア 転職
  default_like_ids: 6588884 6592773
  default_top_n: 5
```

```
2023-12-29 06:08:08,515 - __main__ - INFO - input: [猫と脳波以外のニュース  犬], [], [5]
2023-12-29 06:08:08,515 - src.models.embedder - INFO - encode method: chunk_split
2023-12-29 06:08:08,515 - src.models.embedder - INFO - split sentences to chunks
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 3963.12it/s]
2023-12-29 06:08:08,516 - src.models.embedder - INFO - make weight matrix
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/sbert-news-recommender-RVP9JgU2-py3.10/lib/python3.10/site-packages/gradio/queueing.py", line 489, in call_prediction
    output = await route_utils.call_process_api(
  File "/root/.cache/pypoetry/virtualenvs/sbert-news-recommender-RVP9JgU2-py3.10/lib/python3.10/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/root/.cache/pypoetry/virtualenvs/sbert-news-recommender-RVP9JgU2-py3.10/lib/python3.10/site-packages/gradio/blocks.py", line 1561, in process_api
    result = await self.call_function(
  File "/root/.cache/pypoetry/virtualenvs/sbert-news-recommender-RVP9JgU2-py3.10/lib/python3.10/site-packages/gradio/blocks.py", line 1179, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/root/.cache/pypoetry/virtualenvs/sbert-news-recommender-RVP9JgU2-py3.10/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/.cache/pypoetry/virtualenvs/sbert-news-recommender-RVP9JgU2-py3.10/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/root/.cache/pypoetry/virtualenvs/sbert-news-recommender-RVP9JgU2-py3.10/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/root/.cache/pypoetry/virtualenvs/sbert-news-recommender-RVP9JgU2-py3.10/lib/python3.10/site-packages/gradio/utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
  File "/content/sbert-news-recommender/src/visualization/visualize.py", line 124, in search
    query_embeddings = embedding_query(query)
  File "/content/sbert-news-recommender/src/visualization/visualize.py", line 35, in embedding_query
    query_embeddings = embedder.encode(sentences)
  File "/content/sbert-news-recommender/./src/models/embedder.py", line 56, in encode
    embeddings = self._make_chunk_averaged_encode(sentences)
  File "/content/sbert-news-recommender/./src/models/embedder.py", line 115, in _make_chunk_averaged_encode
    weight_matrix = make_weight_matrix(chunks_list)
  File "/content/sbert-news-recommender/./src/models/embedder.py", line 177, in make_weight_matrix
    assert weight_matrix.sum() == n_size
AssertionError
```

**Comment by u-masao** [comment]
以下のモデルで再現。

intfloat/multilingual-e5-base
intfloat/multilingual-e5-large

**Comment by u-masao** [comment]
スペース文字が連続すると発生することを確認。
