### ISSUE TITLE
検索画面等で利用する Embedding モデルを選択したい

### ISSUE THREAD

**Issue by u-masao** [u-masao/embed-text-recommender#3]
モデル毎の動作を比較するため、Embedding モデルを UI で選択できるようにしたい。
現在は ui.yaml にモデルやベクトルを設定しており、ロード時に読み込んでいる。

UI の再読込処理がキックできれば良いのかもしれない。

**Comment by u-masao** [comment]
Gradio のアプリ内から Gradio インスタンスを初期化するのは難しそう。

と思ったけど、exit() しちゃえば良いのでは？

**Comment by u-masao** [comment]
設定ファイルを修正してから exit() したらどうかな。

**Comment by u-masao** [comment]
起動側で shell スクリプトで死んだら再起動するようにしておいて。

**Comment by u-masao** [comment]
現在、SentenceTransformerとWord2Vecをサポートしている。
この2つを切り替えられるようにしたい。

**Comment by u-masao** [comment]
exit() だけではキレイに終了できないことを確認。

```
ERROR:    Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/masao/.cache/pypoetry/virtualenvs/embed-text-recommender-gNxpm32F-py3.10/lib/python3.10/site-packages/gradio/queueing.py", line 538, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "/home/masao/.cache/pypoetry/virtualenvs/embed-text-recommender-gNxpm32F-py3.10/lib/python3.10/site-packages/gradio/queueing.py", line 489, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/masao/.cache/pypoetry/virtualenvs/embed-text-recommender-gNxpm32F-py3.10/lib/python3.10/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/masao/.cache/pypoetry/virtualenvs/embed-text-recommender-gNxpm32F-py3.10/lib/python3.10/site-packages/gradio/blocks.py", line 1561, in process_api
    result = await self.call_function(
  File "/home/masao/.cache/pypoetry/virtualenvs/embed-text-recommender-gNxpm32F-py3.10/lib/python3.10/site-packages/gradio/blocks.py", line 1179, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/masao/.cache/pypoetry/virtualenvs/embed-text-recommender-gNxpm32F-py3.10/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/masao/.cache/pypoetry/virtualenvs/embed-text-recommender-gNxpm32F-py3.10/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/masao/.cache/pypoetry/virtualenvs/embed-text-recommender-gNxpm32F-py3.10/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/masao/.cache/pypoetry/virtualenvs/embed-text-recommender-gNxpm32F-py3.10/lib/python3.10/site-packages/gradio/utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
  File "/home/masao/work/embed-text-recomender/src/visualization/visualize.py", line 342, in shutdown_application
    exit()
  File "/usr/lib/python3.10/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/masao/.cache/pypoetry/virtualenvs/embed-text-recommender-gNxpm32F-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 686, in lifespan
    await receive()
  File "/home/masao/.cache/pypoetry/virtualenvs/embed-text-recommender-gNxpm32F-py3.10/lib/python3.10/site-packages/uvicorn/lifespan/on.py", line 137, in receive
    return await self.receive_queue.get()
  File "/usr/lib/python3.10/asyncio/queues.py", line 159, in get
    await getter
asyncio.exceptions.CancelledError
```

**Comment by u-masao** [comment]
設定ファイル params.yaml と ui.yaml を駆使すれば SentenceTransformer と Word2Vec を切り替えることができるようになった。

UI で変更できるようにするのは別の機会にしたい。
