### ISSUE TITLE
Workflow 改善: UI 自動リロードに対応すること

### ISSUE THREAD

**Issue by u-masao** [u-masao/embed-text-recommender#55]
以下のようなエラーが表示される。

demo 変数をグローバルで補足できるようにしなければいけない感じがする。

```
Changes detected in: /home/masao/work/embed-text-recommender/src/visualization/visualize.py
Reloading failed. The new demo has a queue and the old one doesn't (or vice versa). Please launch your demo again
```

**Comment by u-masao** [comment]
demo をグローバルにしても以下のエラーが発生する。

自動リロードしなければ動くこともある。

メモリリークも起こりがち。

```
2024-01-04 11:03:35,647 - src.visualization.visualize - INFO - input: [start], [], [], [10]
Traceback (most recent call last):
  File "/home/masao/.cache/pypoetry/virtualenvs/embed-text-recommender-jR2NUJov-py3.10/lib/python3.10/site-packages/gradio/queueing.py", line 489, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/masao/.cache/pypoetry/virtualenvs/embed-text-recommender-jR2NUJov-py3.10/lib/python3.10/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/masao/.cache/pypoetry/virtualenvs/embed-text-recommender-jR2NUJov-py3.10/lib/python3.10/site-packages/gradio/blocks.py", line 1561, in process_api
    result = await self.call_function(
  File "/home/masao/.cache/pypoetry/virtualenvs/embed-text-recommender-jR2NUJov-py3.10/lib/python3.10/site-packages/gradio/blocks.py", line 1179, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/masao/.cache/pypoetry/virtualenvs/embed-text-recommender-jR2NUJov-py3.10/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/masao/.cache/pypoetry/virtualenvs/embed-text-recommender-jR2NUJov-py3.10/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/masao/.cache/pypoetry/virtualenvs/embed-text-recommender-jR2NUJov-py3.10/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/masao/.cache/pypoetry/virtualenvs/embed-text-recommender-jR2NUJov-py3.10/lib/python3.10/site-packages/gradio/utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
  File "/home/masao/work/embed-text-recommender/./src/visualization/visualize.py", line 239, in search
    positive_query_embeddings = embedding_query(positive_query)
  File "/home/masao/work/embed-text-recommender/./src/visualization/visualize.py", line 50, in embedding_query
    query_embeddings = np.zeros(engine.get_embed_dimension())
NameError: name 'engine' is not defined
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/masao/.cache/pypoetry/virtualenvs/embed-text-recommender-jR2NUJov-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/masao/.cache/pypoetry/virtualenvs/embed-text-recommender-jR2NUJov-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/masao/.cache/pypoetry/virtualenvs/embed-text-recommender-jR2NUJov-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/masao/.cache/pypoetry/virtualenvs/embed-text-recommender-jR2NUJov-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/home/masao/.cache/pypoetry/virtualenvs/embed-text-recommender-jR2NUJov-py3.10/lib/python3.10/site-packages/starlette/responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "/home/masao/.cache/pypoetry/virtualenvs/embed-text-recommender-jR2NUJov-py3.10/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/home/masao/.cache/pypoetry/virtualenvs/embed-text-recommender-jR2NUJov-py3.10/lib/python3.10/site-packages/starlette/responses.py", line 273, in wrap
    await func()
  File "/home/masao/.cache/pypoetry/virtualenvs/embed-text-recommender-jR2NUJov-py3.10/lib/python3.10/site-packages/starlette/responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "/home/masao/.cache/pypoetry/virtualenvs/embed-text-recommender-jR2NUJov-py3.10/lib/python3.10/site-packages/gradio/routes.py", line 660, in sse_stream
    raise e
  File "/home/masao/.cache/pypoetry/virtualenvs/embed-text-recommender-jR2NUJov-py3.10/lib/python3.10/site-packages/gradio/routes.py", line 601, in sse_stream
    raise HTTPException(
fastapi.exceptions.HTTPException

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/masao/.cache/pypoetry/virtualenvs/embed-text-recommender-jR2NUJov-py3.10/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/masao/.cache/pypoetry/virtualenvs/embed-text-recommender-jR2NUJov-py3.10/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/masao/.cache/pypoetry/virtualenvs/embed-text-recommender-jR2NUJov-py3.10/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/masao/.cache/pypoetry/virtualenvs/embed-text-recommender-jR2NUJov-py3.10/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/masao/.cache/pypoetry/virtualenvs/embed-text-recommender-jR2NUJov-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/masao/.cache/pypoetry/virtualenvs/embed-text-recommender-jR2NUJov-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/masao/.cache/pypoetry/virtualenvs/embed-text-recommender-jR2NUJov-py3.10/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/home/masao/.cache/pypoetry/virtualenvs/embed-text-recommender-jR2NUJov-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 83, in __call__
    raise RuntimeError(msg) from exc
RuntimeError: Caught handled exception, but response already started.

```
